# Generated by Django 2.1.5 on 2019-03-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190304_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(related_name='abc', to='web.UserInfo', verbose_name='任课老师'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='web.UserInfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultanter', to='web.UserInfo', verbose_name='课程顾问'),
        ),
    ]
