# Generated by Django 2.1.5 on 2019-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190306_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_consult_date',
            field=models.DateField(blank=True, null=True, verbose_name='最后跟进日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='recv_date',
            field=models.DateField(blank=True, null=True, verbose_name='当前课程顾问的接单日期'),
        ),
    ]
