# Generated by Django 2.1.5 on 2019-03-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190306_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='讲师'),
        ),
    ]
